spring.application.name=edadmin

# Database (Direct working config)
spring.datasource.url=jdbc:postgresql://ep-falling-shape-a1yxi0xp-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zZt0hwPMiOl1

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080